-- 1. List the number of films per category.
-- 2. Retrieve the store ID, city, and country for each store.
-- 3. Calculate the total revenue generated by each store in dollars.
-- 4. Determine the average running time of films for each category.

USE sakila;

SELECT fc.category_id, COUNT(title) as num_of_films
FROM sakila.film as f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
GROUP BY fc.category_id
ORDER BY fc.category_id DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, a.city_id, c.country_id
FROM sakila.store AS s
JOIN sakila.address AS a 
ON s.address_id = a.address_id
JOIN sakila.city AS c ON a.city_id = c.city_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM sakila.store s
JOIN sakila.staff ss
ON s.store_id = ss.store_id
JOIN sakila.payment p
ON p.staff_id = ss.staff_id
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.
SELECT fc.category_id, ROUND(AVG(length),2) as 'Average Running Time'
FROM sakila.film as f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
GROUP BY fc.category_id
ORDER BY fc.category_id DESC;

