-- 1. List the number of films per category.
-- 2. Retrieve the store ID, city, and country for each store.
-- 3. Calculate the total revenue generated by each store in dollars.
-- 4. Determine the average running time of films for each category.

USE sakila;

SELECT c.name, COUNT(f.film_id) AS num_of_films
FROM film_category AS fc
JOIN category AS c ON fc.category_id = c.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store AS s
JOIN address AS a 
ON s.address_id = a.address_id
JOIN city AS c ON a.city_id = c.city_id
JOIN country AS co ON c.country_id = co.country_id;


-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, CONCAT('$', FORMAT(SUM(p.amount), 2)) AS total_revenue
FROM sakila.store s
JOIN sakila.staff ss
ON s.store_id = ss.store_id
JOIN sakila.payment p
ON p.staff_id = ss.staff_id
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.
SELECT c.name, ROUND(AVG(length),2) as 'Average Running Time'
FROM film as f
JOIN film_category AS fc
ON f.film_id = fc.film_id
JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name;



